# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-11 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 1, 47, 30, 15054, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
